apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: front
  namespace: monitoring-testing-october24
spec:
  host: front-ng-observability-cloud.fuzzy-broccoli-vwrx9j76wqfww5.github.dev
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: query-frontend
    weight: 100
  wildcardPolicy: None